name: Code formatting

on: [push, pull_request]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-20.04

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Check out the code
        uses: actions/checkout@v2

      - run: cargo fmt --all -- --check
