name: Code formatting

on: [push, pull_request]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-22.04

    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Check out the code
        uses: actions/checkout@v4

      - run: cargo fmt --all -- --check
